In [201]:
import numpy as np
import pdb


class KNN(object):
    
    def __init__(self):
        pass

    def train(self, X, y):
        
        self.X_train = X
        self.y_train = y

    """
    Inputs:
    - X is a numpy array of size (num_examples, D)
    - y is a numpy array of size (num_examples, )
    
    """
        
    def compute_distances(self, X, norm=None):
        """
        Compute the distance between each test point in X and each training point
        in self.X_train.

        Inputs:
        - X: A numpy array of shape (num_test, D) containing test data.
        - norm: the function with which the norm is taken.

        Returns:
        - dists: A numpy array of shape (num_test, num_train) where dists[i, j]
          is the Euclidean distance between the ith test point and the jth training
          point.
        """
        if norm is None:
            norm = lambda x: np.sqrt(np.sum(x**2))
            #norm = 2

        num_test = X.shape[0]
        num_train = self.X_train.shape[0]
        dists = np.zeros((num_test, num_train))
        for i in np.arange(num_test):
            for j in np.arange(num_train):
            # ================================================================ #
            # YOUR CODE HERE:
            #   Compute the distance between the ith test point and the jth       
            #   training point using norm(), and store the result in dists[i, j].     
            # ================================================================ #
                dists[i,j] = np.linalg.norm(self.X_train[j]-X[j])

            # ================================================================ #
            # END YOUR CODE HERE
            # ================================================================ #

        return dists

    def compute_L2_distances_vectorized(self, X):
        """
        Compute the distance between each test point in X and each training point
        in self.X_train WITHOUT using any for loops.

        Inputs:
        - X: A numpy array of shape (num_test, D) containing test data.

        Returns:
        - dists: A numpy array of shape (num_test, num_train) where dists[i, j]
          is the Euclidean distance between the ith test point and the jth training
          point.
        """
        num_test = X.shape[0]
        num_train = self.X_train.shape[0]
        dists = np.zeros((num_test, num_train))

        # ================================================================ #
        # YOUR CODE HERE:
        #   Compute the L2 distance between the ith test point and the jth       
        #   training point and store the result in dists[i, j].  You may 
        #   NOT use a for loop (or list comprehension).  You may only use
        #   numpy operations.
        #
        #   HINT: use broadcasting.  If you have a shape (N,1) array and
        #   a shape (M,) array, adding them together produces a shape (N, M) 
        #   array.
        # ================================================================ #

        x_test_square = np.sum(X**2,axis=1).reshape((num_test,1))
        x_train_square = np.sum(self.X_train**2,axis =1).reshape((1,num_train))
        dot_test_train = np.dot(X,self.X_train.T)
        dists = x_test_square + x_train_square - 2*dot_test_train 
    

        # ================================================================ #
        # END YOUR CODE HERE
        # ================================================================ #

        return dists


    def predict_labels(self, dists, k=1):
        """
        Given a matrix of distances between test points and training points,
        predict a label for each test point.

        Inputs:
        - dists: A numpy array of shape (num_test, num_train) where dists[i, j]
          gives the distance betwen the ith test point and the jth training point.

        Returns:
        - y: A numpy array of shape (num_test,) containing predicted labels for the
          test data, where y[i] is the predicted label for the test point X[i].  
        """
        num_test = dists.shape[0]
        y_pred = np.zeros(num_test)
        for i in np.arange(num_test):
          # A list of length k storing the labels of the k nearest neighbors to
          # the ith test point.
            closest_y = []
          # ================================================================ #
          # YOUR CODE HERE:
          #   Use the distances to calculate and then store the labels of 
          #   the k-nearest neighbors to the ith test point.  The function
          #   numpy.argsort may be useful.
          #   
          #   After doing this, find the most common label of the k-nearest
          #   neighbors.  Store the predicted label of the ith training example
          #   as y_pred[i].  Break ties by choosing the smaller label.
          # ================================================================ #
            closest_y = dists[i].argsort()[0:k]
            class_closest_y = []
            for i in closest_y : 
                class_closest_y.append(self.Y_train[i])
                
                
            y_pred.append(max(set(class_closest_y),key=class_closest_y.count))
            

          # ================================================================ #
          # END YOUR CODE HERE
          # ================================================================ #

        return y_pred


In [133]:
a = np.arange(12)
a = a.reshape((4,3))

In [144]:
b = np.arange(15)
b = b.reshape((5,3))

In [156]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [157]:
b.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [158]:
A = np.sum(a**2, axis=1).reshape((4, 1))
B = np.sum(b**2,axis =1).reshape((1,5))

In [159]:
A

array([[  5],
       [ 50],
       [149],
       [302]])

In [160]:
B

array([[  5,  50, 149, 302, 509]])

In [161]:
dot = np.dot(a, b.T)

In [163]:
dot

array([[  5,  14,  23,  32,  41],
       [ 14,  50,  86, 122, 158],
       [ 23,  86, 149, 212, 275],
       [ 32, 122, 212, 302, 392]])

In [165]:
A 

array([[  5],
       [ 50],
       [149],
       [302]])

In [168]:
B

array([[  5,  50, 149, 302, 509]])

In [167]:
A + B

array([[ 10,  55, 154, 307, 514],
       [ 55, 100, 199, 352, 559],
       [154, 199, 298, 451, 658],
       [307, 352, 451, 604, 811]])

In [164]:
A + B - 2*dot

array([[  0,  27, 108, 243, 432],
       [ 27,   0,  27, 108, 243],
       [108,  27,   0,  27, 108],
       [243, 108,  27,   0,  27]])

In [183]:
a = np.array([[1,4,2,25], [13,1,4,29]])

In [184]:
a.argsort(axis=1)

array([[0, 2, 1, 3],
       [1, 2, 0, 3]])

In [186]:
a

array([[ 1,  4,  2, 25],
       [13,  1,  4, 29]])

In [191]:
y = []
y = a[1].argsort()[0:2]

In [194]:
for i in y : 
    print(i)

1
2


In [200]:
lst = [2, 3, 3, 3, 3, 4, 1, 1, 1, 1, 0,0,0,0,0]
max(set(lst), key=lst.count)

0

In [198]:
set(lst)

{1, 2, 3, 4}